### ISSUE TITLE
linux-aarch64-7ji-headers-6.15.7-1-aarch64.pkg.tar.zst

### ISSUE THREAD

**Issue by Petr1946** [7Ji/archrepo#49]
$ uname -a
Linux alarm 6.16.7 #1 SMP PREEMPT Wed Sep 17 19:01:31 MSK 2025 aarch64 GNU/Linux

$ sudo pacman -U '/home/petr/Downloads/linux-aarch64-7ji-headers-6.15.7-1-aarch64.pkg.tar.zst' 
loading packages...
warning: linux-aarch64-7ji-headers-6.15.7-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) linux-aarch64-7ji-headers-6.15.7-1

Total Installed Size:  101.25 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Running pre-transaction hooks...
(1/1) Remove upgraded DKMS modules
:: Processing package changes...
(1/1) reinstalling linux-aarch64-7ji-headers       [######################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating module dependencies...
(3/3) Install DKMS modules
==> dkms install --no-depmod ast/1.14.2_2 -k 6.15.7-1-aarch64-7ji
Deprecated feature: CLEAN (/var/lib/dkms/ast/1.14.2_2/source/dkms.conf)

Error! Bad return status for module build on kernel: 6.15.7-1-aarch64-7ji (aarch64)
Consult /var/lib/dkms/ast/1.14.2_2/build/make.log for more information.
==> WARNING: `dkms install --no-depmod ast/1.14.2_2 -k 6.15.7-1-aarch64-7ji' exited 10
==> dkms install --no-depmod nvidia/580.82.09 -k 6.15.7-1-aarch64-7ji

Error! Bad return status for module build on kernel: 6.15.7-1-aarch64-7ji (aarch64)
Consult /var/lib/dkms/nvidia/580.82.09/build/make.log for more information.
==> WARNING: `dkms install --no-depmod nvidia/580.82.09 -k 6.15.7-1-aarch64-7ji' exited 10

make.log

DKMS (dkms-3.2.1) make.log for ast/1.14.2_2 for kernel 6.15.7-1-aarch64-7ji (aarch64)
Fri Sep 19 07:23:09 AM MSK 2025

Building module(s)
#   command: make -j8 KERNELRELEASE=6.15.7-1-aarch64-7ji -C /usr/lib/modules/6.15.7-1-aarch64-7ji/build M=/var/lib/dkms/ast/1.14.2_2/build modules
make: Entering directory '/usr/lib/modules/6.15.7-1-aarch64-7ji/build'
make[1]: Entering directory '/var/lib/dkms/ast/1.14.2_2/build'
  CC [M]  ast_drv.o
  CC [M]  ast_i2c.o
  CC [M]  ast_main.o
  CC [M]  ast_mm.o
  CC [M]  ast_mode.o
  CC [M]  ast_post.o
  CC [M]  ast_dp501.o
  CC [M]  ast_dp.o
ast_drv.c:32:10: fatal error: drm/drm_aperture.h: No such file or directory
   32 | #include <drm/drm_aperture.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/lib/modules/6.15.7-1-aarch64-7ji/build/scripts/Makefile.build:203: ast_drv.o] Error 1
make[3]: *** Waiting for unfinished jobs....
ast_post.c:45:6: warning: no previous prototype for ‘ast_disable_vga’ [-Wmissing-prototypes]
   45 | void ast_disable_vga(struct drm_device *dev)
      |      ^~~~~~~~~~~~~~~
ast_mode.c:1352:23: error: initialization of ‘enum drm_mode_status (*)(struct drm_connector *, const struct drm_display_mode *)’ from incompatible pointer type ‘enum drm_mode_status (*)(struct drm_connector *, struct drm_display_mode *)’ [-Wincompatible-pointer-types]
 1352 |         .mode_valid = ast_mode_valid,
      |                       ^~~~~~~~~~~~~~
ast_mode.c:1352:23: note: (near initialization for ‘ast_connector_helper_funcs.mode_valid’)
make[3]: *** [/usr/lib/modules/6.15.7-1-aarch64-7ji/build/scripts/Makefile.build:203: ast_mode.o] Error 1
ast_i2c.c: In function ‘ast_i2c_create’:
ast_i2c.c:123:30: error: ‘I2C_CLASS_DDC’ undeclared (first use in this function); did you mean ‘I2C_CLASS_HWMON’?
  123 |         i2c->adapter.class = I2C_CLASS_DDC;
      |                              ^~~~~~~~~~~~~
      |                              I2C_CLASS_HWMON
ast_i2c.c:123:30: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [/usr/lib/modules/6.15.7-1-aarch64-7ji/build/scripts/Makefile.build:203: ast_i2c.o] Error 1
make[2]: *** [/usr/lib/modules/6.15.7-1-aarch64-7ji/build/Makefile:2003: .] Error 2
make[1]: *** [/usr/lib/modules/6.15.7-1-aarch64-7ji/build/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/ast/1.14.2_2/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.15.7-1-aarch64-7ji/build'

# exit code: 2
# elapsed time: 00:00:04
----------------------------------------------------------------

**Comment by 7Ji** [comment]
https://github.com/torvalds/linux/commit/689274a56c0c088796d359f6c6267323931a2429
